# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: secure_random_url_safe_development
  pool: 5
  username: agencyspotter
  password: agencyspotter
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: secure_random_url_safe_test
  pool: 5
  username: agencyspotter
  password: agencyspotter
  min_messages: WARNING
  
production:
  adapter: postgresql
  encoding: unicode
  database: secure_random_url_safe_development
  pool: 5
  username: agencyspotter
  password: agencyspotter
  min_messages: WARNING